name: kitaabua
description: A kitaabua-french dictionary project with firebase firestore as database.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  get: ^4.6.6
  get_storage: ^2.1.1

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  #firebase_storage: ^11.5.3
  cloud_firestore: ^4.13.5

  #slidable
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/logos/logo.png"
  #image_path_ios: "assets/logos/logo.png"
  #image_path_android: "assets/logos/logo.png"
  android: true
  ios: true
  min_sdk_android: 21
  # You will have to run 'flutter pub run flutter_launcher_icons' to actually change the icons

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
